### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by hopeforkoami** [Nkaleth/Recipe-app#20]
Hi,
We setup the kanban board and here is the link to it  https://github.com/users/Nkaleth/projects/3
members of the group are @Nkaleth  and @hopeforkoami.
Thanks.

**Comment by emmanuellekamwa** [comment]
**STATUS: CHANGES REQUESTED ❌⛔**
Hello @hopeforkoami and @Nkaleth 👋
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive issue

## Required Changes ♻️
-  The Kanban board should contain the To Do, In Progress, In Review, and Done columns respectively but I can't see the In Review column on your board. Please add that.
- Please when writing the points remove the spaces between the square brackets for good presentation.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rotimiazeez** [comment]
Hi @hopeforkoami  and @Nkaleth  👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job implementing the required changes 👍🏽 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
